# Generated by Django 6.1.1 on 2026-09-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('card_image', models.ImageField(upload_to='trips/cards/')),
                ('hero_image', models.ImageField(upload_to='trips/heroes/')),
                ('package_details', models.TextField(blank=True)),
                ('included', models.TextField(blank=True)),
                ('excluded', models.TextField(blank=True)),
                ('important_information', models.TextField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_message', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trips/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.trip')),
            ],
        ),
    ]
