# Generated by Django 6.1.1 on 2026-09-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Go Offroute. See the Unseen.', max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('about_title', models.CharField(default='Travel Beyond The Ordinary.', max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('whatsapp_number_1', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number_2', models.CharField(blank=True, max_length=20)),
                ('instagram_username', models.CharField(default='@offroute.inn', max_length=100)),
                ('instagram_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
