# Generated by Django 6.1.1 on 2026-09-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripitineraryday',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripitineraryday',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tripitineraryday',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
