# Generated by Django 6.1.1 on 2026-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_tripitineraryday_day_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
