# Generated by Django 6.1.1 on 2026-09-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_display_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='whatsapp_number_1',
            new_name='call_number_1',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='whatsapp_number_2',
            new_name='call_number_2',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
